stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build

test:
  stage: test
  script:
    - npm test

deploy:
  stage: deploy
  only:
    - main
  script:
    - ssh -o StrictHostKeyChecking=no $AZURE_VM_USER@$AZURE_VM_IP "
        cd /home/azureuser/my-node-app &&
        git pull origin main &&
        npm install &&
        npm run build &&
        pm2 restart app || pm2 start app.js --name my-node-app
      "
