stages:
  - build
  - test
  - deploy

# Build Stage: Install dependencies
build:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install
  only:
    - main

# Test Stage: Run tests before deployment
test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test || echo "Tests failed! Check logs."

# Deployment Stage: Deploy the Node.js app to Azure VM
deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - echo "Deploying to Azure VM..."
    - ssh $VM_USER@$VM_HOST "cd /home/azureuser/myapp && git pull origin main && npm install && pm2 restart app.js"
  only:
    - main
